---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Insert title of project here"
subtitle: "https://github.com/cmullane94/ENV_872_Project"
author: "Claire Mullaney"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE, knitr::opts_knit$set(root.dir = "/Users/clairemullaney/Desktop/ENV 872/Environmental_Data_Analytics_2020/Project/ENV_872_Project")}
# Set your working directory
getwd()

# Load your packages
library(tidyverse)
library(GGally)
library(nlme)
library(piecewiseSEM)
library(MASS)
library(agricolae)

# Set your ggplot theme
deftheme <- theme_classic(base_size = 14) + 
  theme(axis.text = element_text(color = "black"),
        legend.position = "top") 
theme_set(deftheme)

# Load your datasets
GBR_Sites <- read.csv("./Data/Raw/data.gov.au_fish_benthos_GBR_sites_raw.csv")

```

# Rationale and Research Questions

• Contains clear context for research topic
• Contains rationale for dataset of choice
• Contains one or more questions of an appropriate scope
for the project

As stressors such as ___ increasingly affect coral reefs worldwide, multiple-use zoning is becoming 

This dataset was selected because it is one of the few projects established with the goal of specifically assessing the ecological effects of multiple-use zoning on the inshore coral reefs of the Great Barrier Reef Marine Park (GBRMP). Additionally, it is the only long-term monitoring project with a dataset that was established prior to the implementation of a new zoning management plan in 2004.

This project sought to answer the following questions about the inshore coral reefs of the GBRMP:

1. What variables impact live hard coral cover?
2. What variables impact fish density?
3. Do no-take zones established in 1987, no-take zones established in 2004, and fished zones have different mean amounts of live hard coral cover, fish density, and fish species richness?

\newpage

# Dataset Information

• Describes source and content of data
• Details the wrangling process from raw to processed data
• Contains a table summarizing the dataset structure

\newpage

# Exploratory Analysis 

• Flow between text and visualizations is cohesive
• Relevant exploratory information is visualized

\newpage

# Analysis

• Flow between text and visualizations is cohesive
• Visualizations and statistical tests pertain directly to
specific questions
• Statistical results are reported in plain language with
relevant statistical output in parentheses
• Findings are reported clearly in relation to research
questions

## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions

• Major findings are summarized
• Conclusions relate back to the original research context

\newpage

# References
<add references here if relevant, otherwise delete this section> 
